# Generated by Django 5.1.4 on 2024-12-27 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('description', models.TextField()),
                ('catagory', models.CharField(choices=[('Первая', 'Первая'), ('Вторая', 'Вторая'), ('Третья', 'Третья')], max_length=200, verbose_name='Категория')),
            ],
        ),
    ]
